name: watering

on:
  schedule:
    - cron: '03 15 * * *'
  workflow_dispatch:

jobs:
  water:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          [ -f alternative_water.txt ] || touch alternative_water.txt
          echo "🌊 Watering Updated on $(date +'%Y-%m-%d')" >> alternative_water.txt

      - run: |
          git config --global user.name 'imneko0'
          git config --global user.email 'neko@imnya.ng'
          git add alternative_water.log
          git commit -m "🌊 Watering Updated on $(date +'%Y-%m-%d')"

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
